### PR TITLE
Adding support for semver resolution of services.

### PR DESCRIPTION
**Pull request by allain**
Allows you to create versioned services and then resolving them by using semver ranges.

For example:
Worker#1 a@1.2.3
Worker#2 a@1.2.4

Clients can declare that they require a@~1.2.3 and either of those will match.

### CODE REVIEW

**Comment by allain** [comment]
In case you're curious, this is why I'd like this: https://github.com/allain/servicify

**Comment by prdn** [comment]
Thanks @allain really appreciated :+1:

**Comment by maxired** [comment]
Hi,

This is cool that this feature has been merged.
Still I think that in the long term, we should be able to remove this from the `Router`.
I can say the same regarding the wildcard features that I initiate ;)

IMHO, we should think about a way to extend the router to be able to change the routing algorithm. Providing such a flexibility would be a huge advantage for Pigato. 
@prdn , any opinion on this point ? 

Of course in the meantime, anybody who want a specific routing can 'fake' it , using a special `worker`, retransmitting request to another topic. Thanks to the $dir feature, we can  now detect which nodes are up, and use this information to choose the topic on which we will forward the request.

**Comment by allain** [comment]
@prdn Thank you! 

@maxired Agreed. I look forward to seeing how that's broken out.

**Comment by prdn** [comment]
@allain @maxired please review this issue https://github.com/prdn/pigato/issues/57 and continue there the discussion

**Pull request merged**
