### PR TITLE
First implementation of wildcard

### PR DESCRIPTION
**Pull request by maxired**
Hi,

this is a first try to implement feature requested in https://github.com/prdn/pigato/issues/11.

I'am not sure whether the serviceRequire function is the best place, mainly because its looks like to be called quiet often.

Any feedback is welcome.

### CODE REVIEW

**Comment by prdn** [comment]
Thank you. 
I'll give it a try tomorrow hopefully.

**Comment by maxired** [comment]
Hi,

after more tests, this is NOT READY to be merged. I'll let you know if I find another solution.

**Comment by maxired** [comment]
@prdn , I rebased this on top of commit of yesterday.
Everything seems to be working fine.
Any chance to see this to be merged ?

When I compare to others solutions, 
NATS has a wildcards, but to the best of my knowledge, has no priority mechanisms
https://github.com/apcera/gnatsd/issues/76

**Comment by prdn** [comment]
Thank you. 

Going to test it in these days.

**Pull request closed without merging**
