### PR TITLE
Wip - start/stop acknowlege and Cb + tests 

### PR DESCRIPTION
**Pull request by maxired**
Hi,

You might be interested by some of the following changes.
The commit are simple enough I believed to be easily understood.

I don't expect it to be merged as it,
but as I won't be available in the following weeks to work or discuss about Pigato,
feel free to do what you want with it ;)

### CODE REVIEW

**Comment by prdn** [comment]
Thank you. I think they are interesting but I'll take some time to review them and merge.
Hopefully we'll have you back after some weeks :-)

**Comment by maxired** [comment]
Yes you will ;) 
Take your time and don't hesite to cherry-pick ;)

**Comment by maxired** [comment]
For information, the first commit was because I am used to start a specific test with ```mocha -g '<regexp>'``` , but have been disturbated by stuff happening in a file not even needed for that test.

**Comment by prdn** [comment]
Quite finished to integrate your changes. Tomorrow I'll publish the update

**Comment by maxired** [comment]
Awesome. I should be able to give it a look by the end of next week.

**Comment by maxired** [comment]
Wow, I'm impressed.
Thanks for the good job.

**Comment by prdn** [comment]
All the credits for this commit are yours :-)
Thank you!!

On 22 May 2015 at 15:14, Dalmais Maxence <notifications@github.com> wrote:

> Wow, I'm impressed.
> Thanks for the good job.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prdn/pigato/pull/36#issuecomment-104656554>.
>



-- 
--
Paolo Ardoino

**Pull request merged**
